# Generated by Django 2.1.3 on 2018-11-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_status', models.CharField(default='未缴纳', max_length=10)),
                ('electric_status', models.CharField(default='未缴纳', max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry_exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
