# Generated by Django 2.1.3 on 2018-11-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_check_in_student'),
        ('apartment', '0002_auto_20181119_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_exit',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.Building'),
            preserve_default=False,
        ),
    ]
