# Generated by Django 2.1.3 on 2018-11-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('used', models.IntegerField(default=0)),
                ('room_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Check_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=5)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField()),
                ('used', models.IntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Building')),
            ],
        ),
        migrations.AddField(
            model_name='check_in',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Room'),
        ),
    ]
